name: Deploy FastAPI to Azure Web App - deep-research-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # (Optional) quick sanity check; not required for deploy
      - name: Set up Python (optional)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (optional)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
          # pytest -q  # if you have tests

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7D827099822941309D3AC7A70B49DFE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA8147C58D85469CA6F0CD05BDB0B44D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83D8A7A0065E482CB392B143EDFE7820 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deep-research-app'
          slot-name: 'Production'
          package: './backend'   # deploy only backend folder
